spring:
  data:
    mongodb:
      uri: mongodb+srv://Spring:CdyAxLrVMz3Mu5ln@cluster0.dmenfrs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: microservices
  application:
    name: RATING-SERVICE

  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
